server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: Store
          uri: http://localhost:8082
          predicates:
            - Path=/stores/** 
        - id: Delivery
          uri: http://localhost:8083
          predicates:
            - Path=/deliveries/** 
        - id: Pay
          uri: http://localhost:8084
          predicates:
            - Path=/pays/** 
        - id: CustomerCenter
          uri: http://localhost:8085
          predicates:
            - Path= 
        - id: StoreCenter
          uri: http://localhost:8086
          predicates:
            - Path= 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://order:8080
          predicates:
            - Path=/orders/** 
        - id: Store
          uri: http://store:8080
          predicates:
            - Path=/stores/** 
        - id: Delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/** 
        - id: Pay
          uri: http://pay:8080
          predicates:
            - Path=/pays/** 
        - id: CustomerCenter
          uri: http://customerCenter:8080
          predicates:
            - Path= 
        - id: StoreCenter
          uri: http://storeCenter:8080
          predicates:
            - Path= 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
