apiVersion: apps/v1
kind: Deployment
metadata:
  name: StoreCenter
  labels:
    app: StoreCenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: StoreCenter
  template:
    metadata:
      labels:
        app: StoreCenter
    spec:
      containers:
        - name: StoreCenter
          image: username/StoreCenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5