---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Order
  labels:
    app: Order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Order
  template:
    metadata:
      labels:
        app: Order
    spec:
      containers:
        - name: Order
          image: username/Order:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Store
  labels:
    app: Store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Store
  template:
    metadata:
      labels:
        app: Store
    spec:
      containers:
        - name: Store
          image: username/Store:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Delivery
  labels:
    app: Delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Delivery
  template:
    metadata:
      labels:
        app: Delivery
    spec:
      containers:
        - name: Delivery
          image: username/Delivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Pay
  labels:
    app: Pay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Pay
  template:
    metadata:
      labels:
        app: Pay
    spec:
      containers:
        - name: Pay
          image: username/Pay:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: CustomerCenter
  labels:
    app: CustomerCenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CustomerCenter
  template:
    metadata:
      labels:
        app: CustomerCenter
    spec:
      containers:
        - name: CustomerCenter
          image: username/CustomerCenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: StoreCenter
  labels:
    app: StoreCenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: StoreCenter
  template:
    metadata:
      labels:
        app: StoreCenter
    spec:
      containers:
        - name: StoreCenter
          image: username/StoreCenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Order
  labels:
    app: Order
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Order


---


apiVersion: v1
kind: Service
metadata:
  name: Store
  labels:
    app: Store
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Store


---


apiVersion: v1
kind: Service
metadata:
  name: Delivery
  labels:
    app: Delivery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Delivery


---


apiVersion: v1
kind: Service
metadata:
  name: Pay
  labels:
    app: Pay
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Pay


---


apiVersion: v1
kind: Service
metadata:
  name: CustomerCenter
  labels:
    app: CustomerCenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CustomerCenter


---


apiVersion: v1
kind: Service
metadata:
  name: StoreCenter
  labels:
    app: StoreCenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: StoreCenter

